---
- name: Playbook 1
  hosts: MyLocalVMs

- name: "Play 1: Perform fact gathering on local VMs"
  hosts: MyLocalVMs          # specified in the MyInventory file
  remote_user: vagrant       # note that the user is vagrant for 
                             # vagrant-created VM else use the
                             # appropriate user name

  gather_facts: yes          # We ask Ansible to collect all facts
  become: no            # No need for sudo as we are not installing anything

  tasks:    # the task to be performed (here I am showing the effect of include_)
  - name: Get facts of the VM   # This is just for printing out.
    debug:                      # debug is used for printing information
       var: ansible_facts       # ansible_facts is a built-in variable
                                # that stores the collected value

...